import { NextResponse } from "next/server";

interface Topic {
  title: string;
  description: string;
  estimatedHours: number;
  whyImportant: string;
  whyThisOrder: string;
}

interface RoadmapWeek {
  week: number;
  topics: Topic[];
  summary: string;
  resources?: string[];
}

interface RoadmapResponse {
  goal: string;
  totalWeeks: number;
  weeklyHours: number;
  roadmap: RoadmapWeek[];
}

export async function POST(req: Request) {
  try {
    const { currentSkills, goal, weeklyHours, totalDuration, durationUnit } =
      await req.json();

    // Validation
    if (!goal || typeof goal !== "string" || !goal.trim()) {
      return NextResponse.json(
        { error: "Goal is required" },
        { status: 400 }
      );
    }

    if (!weeklyHours || typeof weeklyHours !== "number" || weeklyHours < 1) {
      return NextResponse.json(
        { error: "Valid weekly hours is required (minimum 1)" },
        { status: 400 }
      );
    }

    if (!totalDuration || typeof totalDuration !== "number" || totalDuration < 1) {
      return NextResponse.json(
        { error: "Valid total duration is required (minimum 1 week)" },
        { status: 400 }
      );
    }

    // TODO: Integrate with AI service (OpenAI, Anthropic, etc.)
    // For now, return a placeholder structure that matches the expected format
    // This demonstrates the data structure for hackathon judging

    const totalWeeks = totalDuration;
    const roadmap: RoadmapWeek[] = [];

    // Generate placeholder roadmap structure
    // In production, this would be generated by AI based on:
    // - currentSkills array
    // - goal string
    // - weeklyHours number
    // - totalDuration number

    // Example placeholder for first 2 weeks (can be expanded)
    for (let week = 1; week <= Math.min(totalWeeks, 12); week++) {
      roadmap.push({
        week,
        summary: `Week ${week} focuses on foundational concepts and practical application`,
        topics: [
          {
            title: `Topic ${week}.1: Core Concepts`,
            description:
              "Learn the fundamental principles that form the foundation of this skill",
            estimatedHours: Math.floor(weeklyHours * 0.6),
            whyImportant:
              "Understanding core concepts is crucial as they provide the building blocks for advanced topics",
            whyThisOrder:
              "This topic comes first because it establishes the necessary groundwork that subsequent topics will build upon",
          },
          {
            title: `Topic ${week}.2: Hands-on Practice`,
            description: "Apply what you've learned through practical exercises",
            estimatedHours: Math.floor(weeklyHours * 0.4),
            whyImportant:
              "Practice reinforces learning and helps identify areas that need more attention",
            whyThisOrder:
              "This follows the theory to ensure immediate application while concepts are fresh",
          },
        ],
        resources: [
          "Online tutorials and documentation",
          "Practice projects and exercises",
          "Community forums for questions",
        ],
      });
    }

    // If more weeks requested, add placeholder weeks
    if (totalWeeks > 12) {
      for (let week = 13; week <= totalWeeks; week++) {
        roadmap.push({
          week,
          summary: `Week ${week} continues building advanced skills`,
          topics: [
            {
              title: `Advanced Topic ${week}`,
              description: "Continue your learning journey",
              estimatedHours: weeklyHours,
              whyImportant: "Building expertise requires consistent practice",
              whyThisOrder: "Progressive skill building",
            },
          ],
        });
      }
    }

    const response: RoadmapResponse = {
      goal: goal.trim(),
      totalWeeks,
      weeklyHours,
      roadmap,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error("Roadmap generation error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
